### ISSUE TITLE
Can't add StratifyQML.UI to Project

### ISSUE THREAD

**Issue by ochagnon** [StratifyLabs/StratifyQML#27]
I checkout this repository to `/Users/oriane/StratifyQML/StratifyLabs/UI` and I try to

```
import StratifyLabs.UI 2.0
```

After I:

- add to `QML_IMPORT_PATH`.
- add to this directory to `qml.qrc`

QtCreator can't find module:

```
qrc:/Page1.qml:2 module "StratifyLabs.UI" is not installed
```

and even:

```
import "/Users/oriane/StratifyQML/StratifyLabs/UI"
```

And I get

```
qrc:/Page1.qml:2 import "/Users/oriane/StratifyQML/StratifyLabs/UI" has no qmldir and no namespace
```

But the file is there:

```
$ file /Users/oriane/StratifyQML/StratifyLabs/UI/qmldir
/Users/oriane/StratifyQML/StratifyLabs/UI/qmldir: ASCII text
```

**Comment by tyler-gilbert** [comment]
Try this:

- In Qt Creator, open the project StratifyQML/StratifyLabs/StratifyLabsUI.pro.
- Then configure the project for a Desktop build and add "install" in the "Make Arguments" box.
- Build the project

Those steps should install the QML library in {QT}/5.8/{compiler}/qml/StratifyLabs.

Once you install the library, you shouldn't need to make any changes to the import path. Qt will discover the library just like it discovers the native libraries. This way also makes it easier to deploy applications because most files are automatically copied using mac/win deployqt.

Please let me know if that works.

**Comment by ochagnon** [comment]
Yes that works, thanks!
