### ISSUE TITLE
can not load by qmlscene

### ISSUE THREAD

**Issue by kitech** [StratifyLabs/StratifyQML#43]
qt 5.10.0

qmlscene  Doc/main.qml

error:
Type Introduction unavailable
...
Cannot override FINAL property

but, test import StratifyLabs.UI 3.0, load ok.

**Comment by tyler-gilbert** [comment]
@kitech 

with qt 5.10, they decided to add "icon" to the native Button. This creates a problem with StratifyLabsUI because we have to change the API to make it work. Qt 5.10 doesn't allow you to revert to the API without the "icon".  Hence 3.0 will work with 5.10 (though the API has changed) but 2.x will not work with 5.10. I have tested 2.0 with 5.9.3.

**Comment by kitech** [comment]
oh, i pick a wrong qt version. thanks.
